repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
      -   id: check-yaml
      -   id: check-added-large-files
  -   repo: https://github.com/ambv/black
      rev: 21.9b0
      hooks:
      -   id: black
          language: python
          types: [python]
#          args: ["--line-length=80"]
  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      -   id: isort
          name: isort (python)
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.7.9
      hooks:
      - id: flake8
#  -   repo: https://github.com/pycqa/pylint
#      rev: pylint-2.6.0
#      hooks:
#      -  id: pylint
#         args: ["--max-line-length=80", "--disable=E1101,R0912"]
  -   repo: local
      hooks:
      -   id: pylint
          name: pylint
          entry: pylint
          language: system
          types: [python]
          args: ["--max-line-length=80", "--disable=E1101,R0912",
                 "--ignore=doc"]
