[tool.black]
    py36 = true
    line-length = 80
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | doc

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
'''
[tool.pylint.MASTER]
ignore-paths = [ ".*/docs", ".*/tests" ]
