[tool.black]
    py36 = true
    line-length = 80
    include = '\.pyi?$'
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
      | doc

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
'''
[tool.pylint.MASTER]
ignore-paths = [ ".*/docs", ".*/*tests" ]

# ".*/docs" - ignores 'docs' dir only if it exists inside any number of directories
# ".*/*tests" - ignores 'tests' dir wherever it exists including the project root
# "docs/.*" - ignores 'docs' dir only if it exists in the project root
